version: "3.3"

services:
  product_db:
    image: postgres:14.1
    container_name: product_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=productservice
      - POSTGRES_USER=puser
      - POSTGRES_PASSWORD=ppasssword
    volumes:
      - product_db_data:/var/lib/postgersql/data/

  product_redis:
    image: redis:7
    container_name: product_redis
    ports:
      - 6379:6379
    volumes:
      - product_redis_data:/data
 
  django_product:
    build:
      context: ./ProductService/
      dockerfile: docker/production.Dockerfile
    container_name: django_product
    command: ProductService/docker/web_entrypoint.sh
    environment:
      - DATABASE_URL=psql://puser:ppasssword@product_db:5432/productservice
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - product_db
      - product_redis
      - rabbitmq
    restart: on-failure

  rabbitmq:
    image: "rabbitmq:alpine"
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
    product_db_data:
    product_redis_data:
